### ISSUE TITLE
[QA] 비로그인 유저 좋아요 버튼 클릭시 동작 제어

### ISSUE THREAD

**Issue by chaaerim** [depromeet/toks-web#358]

**Comment by minsgy** [comment]
@chaaerim @dengoyoon 호옥시 요건 어떤걸까요?

**Comment by chaaerim** [comment]
@minsgy https://5gaeanmal.slack.com/archives/C04HVDY7LFJ/p1696337673656789 qa 채널에서 요 스레드 보시면 될 것 같습니다!
